### ISSUE TITLE
Retro compatibility with first version of ModLoader

### ISSUE THREAD

**Issue by pantolomin** [Ijwu/PhoenixPointModLoader#5]
Some modders have left the game and will probably never update their mods. So there are players who want to keep using their mods and therefore stay with the initial version of ModLoader.

I, as a modder, have therefore to handle two branches of my code. The tested one (with initial ModLoader), and the untested (hopefully working) ModLoader 0.2+ branch.

If retro compatibility is brought to ModLoader, modders will be able to focus developpment on only one version (the most recent) and players will be forced to update their ModLoader version without fear of having mods that don't work anymore.

**Comment by Ijwu** [comment]
Linking #6. Thanks for your efforts.
